package SendingToWhatsapp;


import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import static SendingToWhatsapp.toCSV.area;
import static SendingToWhatsapp.toCSV.phoneno;


/**
 * Libraries required - selenium-java-3.141.59/client-combined-3.141.59 jar and chromedriver for selenium compatible with your chrome version
 *
 * To run this whatsapp sender  -
 * For mac run this command in terminal , this opens chrome in debig mode at port 9222
 * /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222 --no-first-run --no-default-browser-check --user-data-dir=$(mktemp -d -t 'chrome-remote_data_dir')
 *
 * For other operating system check command online and run chrome in debug mode at port 9222
 *
 * Running above command will open new Chrome window
 * Open web.whatsapp in it and login using QR code (required only once)
 * Now run the script anytime you want to send the whatsapp message
 *
 * Whatsapp API to be used - "https://web.whatsapp.com/send?phone="+ PhoneNo +"&text=" + text +"&source&data&app_absent";
 * Replace phone no with mobile no and text with the message you want to send
 */

public class selenium {

    // System Property for Chrome Driver

    public static void main(String[] args) throws InterruptedException {

        //set the path in your computer
        System.setProperty("webdriver.chrome.driver", "C:\\webdrivers");

        ChromeOptions options = new ChromeOptions();
        options.setExperimentalOption("debuggerAddress", "127.0.0.1:9515");
        WebDriver driver = new ChromeDriver(options);


        String no = "918953319660";
        String data[] = {"918953319660", "918953319660"};

        String text = "This message is selenium autogenerated for testing - test3";

        String spamtext = text;
        System.out.println("here");

        for (int i = 0; i < data.length; i++) {

            try {

                String path = "https://web.whatsapp.com/send?phone=" + phoneno + "&text=this is to be send" + area;
                driver.get(path);

                if (i > 0) {
                    Alert alert = driver.switchTo().alert();
                    System.out.println("Alert text  " + alert.getText());
                    alert.accept();
                }

                //wait for web whatsapp page to load
                Thread.sleep(15000);

                //select the current active element and press enter key
                System.out.println("Executing press key");
                WebElement element = driver.switchTo().activeElement();
                element.sendKeys(Keys.RETURN);

            } catch (Exception ex) {
                System.out.println("Exception in sending whatsapp message " + ex);
                System.out.println("Retrying to send whatsapp message");

                //stop the main thread for 1 minute, and then proceed
                Thread.sleep(60000);
                i--;
            }
        }
    }

}


